jeremyshannon/Exile

mods/tech/plant_crafts.lua

log entry slipped through, now disabled

mod/tech: removed log, baking progress

---

.gitmodules
game.conf

Remove hard external dependency of naturalslopeslib and add it into the repository as a git submodule

---

mods/backpacks/README.txt
mods/backpacks/init.lua
mods/tech/backpacks.lua

Minor - Fixed typo in backpack function

Recipe cleanup

---

mods/health/food.lua

fix hunger value for maraka cake and burned maraka cake

fix hunger values

---

mods/tech/earthen_building.lua

Possibly we could also have a loose wattle door frame, for aesthetics purposes, but that may be unnecessary.

Make loose wattle connect to doorframes.

---

mods/mapgen/deco.lua

- my work from 2021-07-22
- uses data-table list layout for node decorations
- implements iterative registration of node decorations
- still needs iterative registration of animal eggs

improve `deco.lua`

---

mods/lore/init.lua
mods/lore/suicide.lua

Ib suicide

---

README.md

A more-modest `pull request` where I have written something hopefully actually useful. :-)

Improvements to `README.md`

---

mods/tech/glassworking.lua

Added proper selection_box entries for glass bottles

---

mods/minimal/protection.lua
mods/tech/craft_stations.lua

Added minimal.protection_after_place_node() to crafting stations.
corrected a broken call to S() for minetest.get_translator() call.
not sure it's being used properly. removing for now.

Added protection to crafting station + bug fix

---

mods/artifacts/transporter.lua

fixes problem of power cores loosing ownership when swapped on transporter use.

Transporter fixes

---

mods/artifacts/materials.lua
mods/ncrafting/dyes.lua

Added protection after place callbacks

Added protection to *stone items and dye crafting stations

---

mods/wielded_light/init.lua

Added tall plants to lit nods and corrected water lit nodes showing up
in creative inventory

Added tall plants to lightable nodes; fixed creative inventory

---

mods/wielded_light/init.lua

This fixes receiving lit versions of nodes.

bug fix - drop original node not lit version

---

mods/tech/doors.lua

Wasn't protected for some reason.  Corrected.

Added protection to trapdoor_iron

---

mods/artifacts/art.lua
mods/artifacts/bell.lua
mods/artifacts/materials.lua
mods/artifacts/wayfinder.lua
mods/tech/glassworking.lua

started adding protection to glass bottles but commented them out as
infotext bugs to deal with.  protection also added for
Moonglass and antiquorium blocks.

Added protection to statues,bell,waystone,glass,etc

---

mods/tech/glassworking.lua

Missed adding protection to windows

---

mods/animals/gundu.lua

Dive to avoid heat and cold surface

Gundu responds to out of range temp

---

mods/wielded_light/init.lua

SmallJoker on Github recommended these changes to the PR initially sent
upstream.  Applying them to our branch.

Corrections recommened for PR sent to upstream

---

mods/nodes_nature/trees.lua

Ok, this should be correctly based on master.

Tree nut fix -- master

---

mods/climate/temperature.lua

Replaced with minetest.settings:get()

Bug fix - minetest.setting_get() depricated

---

mods/lore/init.lua
mods/lore/restart.lua

I'll play with creating a recovery inventory at a future date. this at least fixes issue #164

Suicide redo

---

mods/minimal/utility.lua
mods/nodes_nature/liquids.lua
mods/stairs/init.lua
mods/tech/earthen_building.lua
mods/tech/fires.lua

wasn't returning call to slabs_combine so item stack changes not taking effect for redirect from on_place in stairs mod.  Adjusted all to specify a return of slabs_combine()

Bug fix on slabs_combine for thatch

---

mods/nodes_nature/data_plant.lua
mods/nodes_nature/life.lua
mods/tech/tools.lua

Simple change to make knife not dig soil anymore.  sets dig time to 100 so nearly forever
Only needed for crumbly, but knife shouldn't be digging choppy either so set it for that also.  Seems to work well.

make knife not dig dirt

---

mods/artifacts/transporter.lua

Thought I sent this in a pr before but maybe not.  incorrect param nil passed.

Bug fix - server crash on transporter infotext bug
